### ISSUE TITLE
How about 2 spaces tab?

### ISSUE THREAD

**Issue by houd1ni** [Moelf/Telegrambot.jl#4]
I've faced the same task, suprisingly found this repo, seen the code and wanna participate, but it differs from my usual codestyle (primarily golang & javascript tho).

I understand, that it's a bit strange proposal, 2 spaces tabs make code far more compact in the case of deep folding. How do you feel about this? Thanks!

**Comment by Moelf** [comment]
I don't have a strong preference regarding such subtleties

But it seems the community also have discussed this
https://github.com/JuliaEditorSupport/atom-language-julia/issues/76
