### ISSUE TITLE
Receiving warnings for the /start command and improve warning message

### ISSUE THREAD

**Issue by TestSubjector** [Moelf/Telegrambot.jl#5]
Hello, I'm a new user to this library. 
My issue is that when using the /start command, I get the following warning in the console
```
Warning: Command may got passed empty parameter
└ @ Telegrambot ~/.julia/packages/Telegrambot/gzwL3/src/Telegrambot.jl:42
```
After looking at the code, it seems that all commands require an extra parameter to be passed (otherwise the console log will be quickly filled with warnings). 
This seems like an unnecessary restriction, so any workaround for it? 

Additionally, the warning messages could be slightly improved I believe, i.e
```julia
@warn "Not a command start with /"
...
@warn "Command may got passed empty parameter"
```
to some thing like

```julia
@warn "Given command does not start with /"
...
@warn "Given command may have been passed an empty parameter"
```

**Comment by Moelf** [comment]
hum, I didn't really look at the console when making this, so I don't know what the warning is about. But if you have anything particular (e.g use case for console msg, breaking issue) in mind I can see what I can do.

**Comment by Moelf** [comment]
Ah, I think you just need to comment out those 2 lines of warning since it does not change what user will get (i.e nothing).

They were there just to make sure the loop does not crash.

**Comment by TestSubjector** [comment]
This 2 lines I believe - 
https://github.com/Moelf/Telegrambot.jl/blob/872161e72934548a80f54c6f6817831aebe60784/src/Telegrambot.jl#L41-L42
I can even use something like [Suppressor.jl](https://github.com/JuliaIO/Suppressor.jl) from my side to prevent the annoying warnings.

More importantly though, I seem to have found a bigger issue. 
The thing with what you mentioned is that the loop will still crash nevertheless, as after the catch the rest of the code in the loop will still execute. 
So Telegram will still receive a empty parameter for a non-empty parameter command and give a bad request error.

For example, if I use the example given in the README.md and from the side of the bot enter the command `/repeat_msg` (without any other user input), I receive - 
```
┌ Warning: Command may got passed empty parameter
└ @ Telegrambot ~/.julia/packages/Telegrambot/gzwL3/src/Telegrambot.jl:42
ERROR: HTTP.ExceptionRequest.StatusError(400, HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
*some extra info*
{"ok":false,"error_code":400,"description":"Bad Request: message must be non-empty"}""")
```
Now, the kicker is that after restarting the code, I will still receive this error in a few seconds automatically. I believe this is because the command (`/repeat_msg`) is still received at https://github.com/Moelf/Telegrambot.jl/blob/872161e72934548a80f54c6f6817831aebe60784/src/Telegrambot.jl#L20 and so the error repeats.

One way to fix that is to comment out the line `txtCmds["repeat_msg"] = echo` for one run of the code; to flush out the command.
Can you check if this is replicable on your setup?

**Comment by Moelf** [comment]
I see. What you are saying makes sense to me. If you want you can definitely implement something in the `catch` that prevents the loop from executing the empty parameter and maybe (by default) send the end user(or just a `warn` in the console) a msg like 'you need to provide an argument for this cmd'.

**Comment by TestSubjector** [comment]
Sure, I'll try to work on it and send a PR when done.

**Comment by Moelf** [comment]
Fixed in https://github.com/Moelf/Telegrambot.jl/commit/d9a081f378d8e5ba5a461332005faf292885dfec
